In [5]:
from PIL import Image
import numpy as np

a = np.zeros((256,256),np.uint8)
im1 = Image.fromarray(a)

im1.show()

In [6]:
a[128][128] = 255
im1 = Image.fromarray(a)

im1.show()

In [7]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if i == j:
            a[i][j] = 255
im1 = Image.fromarray(a)

im1.show()

In [24]:
im2 = Image.open('parrot.png')

im2.show()

In [25]:
print(im2.getpixel((50,50)))

237


In [8]:
a2 = np.array(im2)
print(a2)

[[  0   0   0 ...   3   0   0]
 [  0   0   0 ...  33  13   0]
 [  4   1   0 ...  96  65   6]
 ...
 [124 133 139 ...  33  13   8]
 [128 138 145 ...  35  28  28]
 [135 137 136 ...  35  28  34]]
