In [1]:
from PIL import Image
import numpy as np

im1 = Image.open('parrot.png')
a = np.array(im1)
print(a)
im1.show()
print(im1.size)

[[  0   0   0 ...   3   0   0]
 [  0   0   0 ...  33  13   0]
 [  4   1   0 ...  96  65   6]
 ...
 [124 133 139 ...  33  13   8]
 [128 138 145 ...  35  28  28]
 [135 137 136 ...  35  28  34]]
(150, 200)


In [2]:
for i in range(im1.size[0]):
    for j in range(im1.size[1]):
        im1.putpixel((i,j),255-im1.getpixel((i,j)))
im1.show()