In [10]:
import numpy as np

a = np.array([[1,1,1,1,1],[1,0,0,0,0],[1,1,1,0,0],[1,0,0,0,0],[1,0,0,0,0]])
t = np.array([[1.5,0,0],[0,1,0],[0,0,1]])
b = np.zeros((int(a.shape[0]*1.5),int(a.shape[1])), dtype=np.int16 )
for x in range(a.shape[0]):
    for y in range(a.shape[1]):
        axy = np.array([[x],[y],[1]])
        bxy = t @ axy
        print('xa,ya =',x,y,' --> xb,yb =',bxy[0][0],bxy[1][0])
        b[int(bxy[0][0]),int(bxy[1][0])] = a[x][y]

xa,ya = 0 0  --> xb,yb = 0.0 0.0
xa,ya = 0 1  --> xb,yb = 0.0 1.0
xa,ya = 0 2  --> xb,yb = 0.0 2.0
xa,ya = 0 3  --> xb,yb = 0.0 3.0
xa,ya = 0 4  --> xb,yb = 0.0 4.0
xa,ya = 1 0  --> xb,yb = 1.5 0.0
xa,ya = 1 1  --> xb,yb = 1.5 1.0
xa,ya = 1 2  --> xb,yb = 1.5 2.0
xa,ya = 1 3  --> xb,yb = 1.5 3.0
xa,ya = 1 4  --> xb,yb = 1.5 4.0
xa,ya = 2 0  --> xb,yb = 3.0 0.0
xa,ya = 2 1  --> xb,yb = 3.0 1.0
xa,ya = 2 2  --> xb,yb = 3.0 2.0
xa,ya = 2 3  --> xb,yb = 3.0 3.0
xa,ya = 2 4  --> xb,yb = 3.0 4.0
xa,ya = 3 0  --> xb,yb = 4.5 0.0
xa,ya = 3 1  --> xb,yb = 4.5 1.0
xa,ya = 3 2  --> xb,yb = 4.5 2.0
xa,ya = 3 3  --> xb,yb = 4.5 3.0
xa,ya = 3 4  --> xb,yb = 4.5 4.0
xa,ya = 4 0  --> xb,yb = 6.0 0.0
xa,ya = 4 1  --> xb,yb = 6.0 1.0
xa,ya = 4 2  --> xb,yb = 6.0 2.0
xa,ya = 4 3  --> xb,yb = 6.0 3.0
xa,ya = 4 4  --> xb,yb = 6.0 4.0


In [9]:
print(b)

[[1 1 1 1 1]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]]
